package com.br.volleyhub.domain.enums;

public enum MotivoPonto {
    ACE,
    ERRO_ADVERSARIO,
    ERRO_ATAQUE,
    ERRO_RECEPCAO,
    ERRO_SAQUE,
    ANTENA,
    DOIS_TOQUES,
    TOQUE_NA_REDE,
    CONDUCAO,
    LINHA,
    QUATRO_TOQUES,
    ATAQUE_IRREGULAR,
    DIGITAL,
    INVASAO_INTERFERENCIA,
    BLOQUEIO_SAQUE,
    ORDEM_SAQUE_INCORRETA,
    TOQUE_ESPACO_ADVERSARIO,
    ATAQUE_MAO_ABERTA,
    LEVANTAMENTO_IRREGULAR,
    ATAQUE,
    BLOQUEIO,
    SAQUE_FORCADO,
    OUTRO
}
